#!/bin/bash
# AYESEC:POST_SHS('18 lines')=9da1fc9afc1b85e1e81e78a53f97d4436d886182eec170ddd6c78ec71e64113d9ade4fd1bf969ed5bbe62baed9a575d2b5e3ccdc0383c27eb7a4b6bc71965afe
# AYESEC:STATUTORY_HEADER
if [ "${ayevdi_sourcefrom}" != "${HOME}/.ayevdi/ayevdi-sourcefrom" ]
then
  echo "AyeVDI by https://ayeai.xyz"
  echo "Copyright (C) 2019-2020 Abhishek Choudhary, Dr Srija Katta"
  echo ""
  echo "NO WARRANTY, and ZERO LIABILITY (Limited to INR 1/- only)"
  echo "Further usage of these software, artifacts or methods"
  echo "are subject to the 'latest' license agreement avaialble at"
  echo "https://raw.githubusercontent.com/ayeai/spl/master/LICENSE"
  echo ""
  echo "AyeVDI not activated. Please use the following command to"
  echo "activate AyeVDI"
  echo '  ayesh=$(tempfile) && wget https://bit.ly/ayevdi-sfrom-init -O${ayesh} -q && . ${ayesh}'
  echo ""
  exit
fi
# AYESEC:STATUTORY_HEADER_COMPLETED
# AYESEC:PREV_SHS('18 lines')=9da1fc9afc1b85e1e81e78a53f97d4436d886182eec170ddd6c78ec71e64113d9ade4fd1bf969ed5bbe62baed9a575d2b5e3ccdc0383c27eb7a4b6bc71965afe

# TODO: Replace extip with fully qualified name
export extip=$(dig @resolver1.opendns.com ANY myip.opendns.com +short)

# Start only if not found
wget --no-cache -O/dev/null -q http://${extip}:6080/vnc_auto.html
if [ $? -gt 0 ]
then

  # Clear the older VNC logs
  export tmpfldr=${HOME}/.vnc/$(date +%s)
  mkdir -p ${tmpfldr}
  mv -f ${HOME}/.vnc/*.log ${tmpfldr}
  mv -f ${HOME}/.ayevdi/ayevdi-gui-${USER}.log ${HOME}/.ayevdi/ayevdi-gui-${USER}.log.$(date +%s)

  # Kill all VNC sessions
  # TBD: Is it a fair policy to allow only 1 VNC session per host? Disabling till decided
  # vncserver --kill :*

  # Daemonize GUI service
  sourcefrom https://bit.ly/ayevdi-daemon-start "ayevdi-gui-${USER}" 'sourcefrom https://bit.ly/ayevdi-gui-init'

  # Wait for VNC server to be ready
  # TODO: This can get into a busy wait - set max limit
  # TBD: What should be the timeout limit?
  while [ $(if [ -e ${HOME}/.vnc/*.log ]; then cat ${HOME}/.vnc/*.log; fi | grep 'created VNC server' | wc -l) -lt 1 ]
  do
    echo Waiting for VNC server...
    sleep 1
  done

  # Wait for noVNC / websockify to be ready
  wget --no-cache -O/dev/null -q http://${extip}:6080/vnc_auto.html
  while [ $? -gt 0 ]
  do
    echo Waiting for noVNC / websockify...
    sleep 1
    wget --no-cache -O/dev/null -q http://${extip}:6080/vnc_auto.html
  done

fi

echo "http://${extip}:6080/vnc_auto.html is the GUI console"

# TODO: The above output may be misleading in some cases of errors - Fix
# TODO: Handle errors
