#!/bin/bash
# AYESEC:POST_SHS('64 lines')=e785940040e33493187af61d1b671d97469bb6f5e3152cee80ade863c5da6d53c4eceb05bd4d195699884355b10513c52617dce97142187a6138fc0d8861ce2d
# AYESEC:FILE_TOP('ayevdi/doc/ayevdi-mascot')

# AYESEC:POST_SHS('18 lines')=9da1fc9afc1b85e1e81e78a53f97d4436d886182eec170ddd6c78ec71e64113d9ade4fd1bf969ed5bbe62baed9a575d2b5e3ccdc0383c27eb7a4b6bc71965afe
# AYESEC:STATUTORY_HEADER
if [ "${ayevdi_sourcefrom}" != "${HOME}/.ayevdi/ayevdi-sourcefrom" ]
then
  echo "AyeVDI by https://ayeai.xyz"
  echo "Copyright (C) 2019-2020 Abhishek Choudhary, Dr Srija Katta"
  echo ""
  echo "NO WARRANTY, and ZERO LIABILITY (Limited to INR 1/- only)"
  echo "Further usage of these software, artifacts or methods"
  echo "are subject to the 'latest' license agreement avaialble at"
  echo "https://raw.githubusercontent.com/ayeai/spl/master/LICENSE"
  echo ""
  echo "AyeVDI not activated. Please use the following command to"
  echo "activate AyeVDI"
  echo '  ayesh=$(tempfile) && wget https://bit.ly/ayevdi-sfrom-init -O${ayesh} -q && . ${ayesh}'
  echo ""
  exit
fi
# AYESEC:STATUTORY_HEADER_COMPLETED
# AYESEC:PREV_SHS('18 lines')=9da1fc9afc1b85e1e81e78a53f97d4436d886182eec170ddd6c78ec71e64113d9ade4fd1bf969ed5bbe62baed9a575d2b5e3ccdc0383c27eb7a4b6bc71965afe

# AYESEC:POST_SHS('37 lines')=53d674d0ebea19d9256ac7e72caadb4779d971776e1826af5f7142c8cd702708a209eddcb9769a62bc9817a5ceee7ab965641cdba9eb10a17b69df59d22161ee
# AYESEC:REPRESENTATION_NOTICE_START

# AYESEC:POST_SHS('11 lines')=6b666aaa94f5a98de2a057ab1b492b552db74aa9fa2f0c7be9714cb39c13a6da20133d70ac169cc1c255a28315465394c0f677bea5a068f0741f3744efc38382
# AYESEC:DRIKSH_START
#                     AyeVDI   ##@###&
#                 /^^^^^^^"""####  o ##:
#                /      Driksh      ##''
#                (  The Immutable  ##{,,
#                { \   /++++++++/  #### 
#                  /  /  \     /  /  \  
#                 /__/ \__\   /__/ \__\ 
# (C) Copyright 2019-2020 Abhishek Choudhary, Dr Srija Katta
#   All rights reserved. MADE IN INDIA | BHARAT MEIN NIRMIT
#                      भारत में निर्मित
# AYESEC:DRIKSH_COMPLETE
# AYESEC:PREV_SHS('11 lines')=e265c3aa4c59b5cdb44f55f18618826fce794e0c94884f7fa89d5a59644b0d0040dc4e95e689a64ee2bd3042b99689c1ebd775e9391761b71c77cd6a6f19c0d3

# NOTICE: This above lines 30-40 are NOT TO BE USED IN DERIVATIVES.
# The above artwork, the business marks AyeVDI, Driksh, and 
# the tagline 'Driksh - The Immutable' are intellectual property
# of Abhishek Choudhary (the original author) and may not be
# reproduced without permission. All rights including media
# and cinematic rights reserved. Derivatives must replace the
# artwork, logo, representation, trademarks appropriately,
# without violating the terms and conditions of the license
# agreement. Unmodified distributions must carry the above lines
# as is. Subject to the jurisdiction on courts in
# Hyderabad, Telangana, India only.
#
# Driksh in Sanskrit is close in meaning to manifestation

# The following command is the only valid method of displaying
# the AyeVDI and Driksh - The Immutable business marks with the
# lion graphic device. It must be executed on inside a bash shell
# on a color capable terminal with lolcat version 42.0.99 installed.
if [ ! -e /usr/games/lolcat ]
then
  wget https://bit.ly/ayevdi-mascot -O- -q | head -39 | tail -9 | cut -c 3- 
  # This script has a dependency on lolcat. If its not installed
  # then we must advise the user to install it
  echo "AyeVDI uses lolcat to colorify some of its output, however"
  echo "it does not appear to be installed on this system or its not"
  echo "available in the executables' path. You may wish to install it"
  echo "with the following command -"
  echo "    sudo apt update && sudo apt install -y lolcat"
  echo ""
  echo "Alternatively, you may want to perform a more thorough setup with"
  echo "the command below, and it will install lolcat along with the rest"
  echo "of the necessary libraries and tools required."
  echo "    sourcefrom https://bit.ly/ayevdi-node-setup"
  echo ""
else
  wget https://bit.ly/ayevdi-mascot -O- -q | head -39 | tail -9 | cut -c 3- | /usr/games/lolcat -F 0.7 -S 2020 -p 20
fi

# AYESEC:REPRESENTATION_NOTICE_COMPLETE
# AYESEC:PREV_SHS('37 lines')=e322f9f2cfd4cc13397edfd9b3e0f7ad7afe10beb96739d4995617ad595c6b2549c553980f4b91ac3fe4c53607c19d956c2663b4b809e1c0f3f85eb0eee9edc6

# AYESEC:FILE_END('ayevdi/doc/ayevdi-mascot')
# AYESEC:PREV_SHS('64 lines')=c9e0dc58da266c8a6a150d64864d315ac674072b72f928240b53aebab718d32c09b608b79859ef249a1ea41520471a517a19cf25cfa99b3b734d2a5336585466
