#!/bin//bash
# AYESEC:POST_SHS('18 lines')=9da1fc9afc1b85e1e81e78a53f97d4436d886182eec170ddd6c78ec71e64113d9ade4fd1bf969ed5bbe62baed9a575d2b5e3ccdc0383c27eb7a4b6bc71965afe
# AYESEC:STATUTORY_HEADER
if [ "${ayevdi_sourcefrom}" != "${HOME}/.ayevdi/ayevdi-sourcefrom" ]
then
  echo "AyeVDI by https://ayeai.xyz"
  echo "Copyright (C) 2019-2020 Abhishek Choudhary, Dr Srija Katta"
  echo ""
  echo "NO WARRANTY, and ZERO LIABILITY (Limited to INR 1/- only)"
  echo "Further usage of these software, artifacts or methods"
  echo "are subject to the 'latest' license agreement avaialble at"
  echo "https://raw.githubusercontent.com/ayeai/spl/master/LICENSE"
  echo ""
  echo "AyeVDI not activated. Please use the following command to"
  echo "activate AyeVDI"
  echo '  ayesh=$(tempfile) && wget https://bit.ly/ayevdi-sfrom-init -O${ayesh} -q && . ${ayesh}'
  echo ""
  exit
fi
# AYESEC:STATUTORY_HEADER_COMPLETED
# AYESEC:PREV_SHS('18 lines')=9da1fc9afc1b85e1e81e78a53f97d4436d886182eec170ddd6c78ec71e64113d9ade4fd1bf969ed5bbe62baed9a575d2b5e3ccdc0383c27eb7a4b6bc71965afe

mkdir -p ${HOME}/.ayevdi/repo

#Lets ensure we've got a fresh clone of the repo
if [ -e ${HOME}/.ayevdi/repo/ayevdi ]
then
  mv ${HOME}/.ayevdi/repo/ayevdi ${HOME}/.ayevdi/repo/ayevdi_$(date +%s)
fi

if [ "${2}" == "" ]
then
  export ayevdi_repo=https://github.com/ayevdi/ayevdi
else
  export ayevdi_repo=${2}
fi
git clone ${ayevdi_repo} ${HOME}/.ayevdi/repo/ayevdi
  
pushd ${HOME}/.ayevdi/repo/ayevdi

  export tmpurls=$(tempfile)
  export ayevdilocalport=8000
  mkdir -p ${HOME}/.ayevdi/local
  for n in $(find . -type f | grep -v .git | xargs cat | tr "()' =;," '\n\n\n\n\n\n\n' | grep bit.ly | grep http | sort -ur)
  do
    printf "%s," ${n}
    echo http://127.0.0.1:${ayevdilocalport}/$(echo ${n} | cut -d'/' -f4,5)
    wget -q ${n} -P ${HOME}/.ayevdi/local
  done >${tmpurls}

  # TODO: The local webroot files should link to the local repo - that will allow may dev use cases
  pushd ${HOME}/.ayevdi/local
  find . -type f | grep -v .git | xargs -n1 -I{} sed -i "$(cat ${tmpurls} | sed 's/\//\\\//g' |\
    awk -vp1=s/ -vp2=/ -vp3=/g\;\  -F',' '{printf p1 $1 p2 $2 p3}')" {}
    screen -S "ayevdi-service-local" -d -m python -m SimpleHTTPServer
  popd

popd
