#!/bin/bash
# AYESEC:POST_SHS('18 lines')=9da1fc9afc1b85e1e81e78a53f97d4436d886182eec170ddd6c78ec71e64113d9ade4fd1bf969ed5bbe62baed9a575d2b5e3ccdc0383c27eb7a4b6bc71965afe
# AYESEC:STATUTORY_HEADER
if [ "${ayevdi_sourcefrom}" != "${HOME}/.ayevdi/ayevdi-sourcefrom" ]
then
  echo "AyeVDI by https://ayeai.xyz"
  echo "Copyright (C) 2019-2020 Abhishek Choudhary, Dr Srija Katta"
  echo ""
  echo "NO WARRANTY, and ZERO LIABILITY (Limited to INR 1/- only)"
  echo "Further usage of these software, artifacts or methods"
  echo "are subject to the 'latest' license agreement avaialble at"
  echo "https://raw.githubusercontent.com/ayeai/spl/master/LICENSE"
  echo ""
  echo "AyeVDI not activated. Please use the following command to"
  echo "activate AyeVDI"
  echo '  ayesh=$(tempfile) && wget https://bit.ly/ayevdi-sfrom-init -O${ayesh} -q && . ${ayesh}'
  echo ""
  exit
fi
# AYESEC:STATUTORY_HEADER_COMPLETED
# AYESEC:PREV_SHS('18 lines')=9da1fc9afc1b85e1e81e78a53f97d4436d886182eec170ddd6c78ec71e64113d9ade4fd1bf969ed5bbe62baed9a575d2b5e3ccdc0383c27eb7a4b6bc71965afe

docker stop $(docker ps -aq)
docker rm $(docker ps -aq)
for i in {1..5}
do
  docker run --name ayetest_${i} -dt ayeai/ayevdi:$(sourcefrom https://bit.ly/ayevdi-image-common)
done
docker exec -it ayetest_2 apt purge -y lsof

sourcefrom https://bit.ly/ayevdi-node-stop-abandoned

echo Waiting for containers to mature
sleep 60

sourcefrom https://bit.ly/ayevdi-node-stop-abandoned

tmpres=$(tempfile)
cat .ayevdi/ayevdi-log | grep POLICY | tail -10 > ${tmpres}
export comp=$(cat ${tmpres} | grep Compliant | wc -l)
export rouge=$(cat ${tmpres} | grep Rouge | wc -l)

if [ $comp -eq 4 ] && [ $rouge -eq 1 ]
then
  echo SUCCESS
else 
  echo FAIL
fi
